export { default as Warning } from './031-warning-24.svg?react'
export { default as Approve } from './054-done-24.svg?react'
export { default as Delete } from './093-delete-16.svg?react'
export { default as AddThin } from './103-add-16.svg?react'
export { default as Info } from './018-info-16.svg?react'
export { default as Arrow } from './143-arrow-16.svg?react'
